export {Profile} from "./Profile"
export {Contact} from "./contact"
export {Data} from "./data"
export {EditData} from "./editData"
export {Information} from "./information"
export * from "./profileLeftBlock"
export * from "./profileRightBlock"
